server:
  port: 3000
  servlet:
    context-path: /api
  error:
    include-stacktrace: never
    include-message: never
    include-binding-errors: never
    include-exception: false

spring:
  application:
    name: ddd-empty-skeleton
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ddd-empty-skeleton?serverTimezone=UTC
    username: root
    password: pass
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: blog
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}
    exchange: ${RABBIT_EXCHANGE:domain_events}
