version: '3'
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: ddd-empty-skeleton
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"